### ISSUE TITLE
how do I install and run on Linux?

### ISSUE THREAD

**Issue by ralyodio** [sentient-engineering/jobber#4]

**Comment by ralyodio** [comment]
`sudo /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222`

This is for mac only.

**Comment by ralyodio** [comment]
```
$ python -u -m jobber.main
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ettinger/src/tmp/jobber/jobber/main.py", line 3, in <module>
    from jobber.core.system_orchestrator import SystemOrchestrator
  File "/home/ettinger/src/tmp/jobber/jobber/core/system_orchestrator.py", line 3, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
```

Need a requirements.txt file for pip installs.

**Comment by nischalj10** [comment]
yeah, in the process of improving setup docs for other platform. you can refer to this PR https://github.com/sentient-engineering/jobber/pull/2 as a starting point. You can use poetry install in absence of requirements.txt

**Comment by nischalj10** [comment]
you can get an API key [here](https://www.langchain.com/langsmith) for free. will be making tracing optional

**Comment by ralyodio** [comment]
where do i put my resume?

**Comment by nischalj10** [comment]
you can add the path to your resume and your details in the [user_preferences.txt](https://github.com/sentient-engineering/jobber/blob/main/jobber/user_preferences/user_preferences.txt) file

**Comment by nischalj10** [comment]
@ralyodio - I have updated the readme for more clarity on how to properly setup and run jobber. please have a look and let me know if you'd like help with anything else!
